import React from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { motion } from 'framer-motion';
import { Wallet, Sparkles, TrendingUp, ShieldCheck, ArrowRight, BellRing } from 'lucide-react';

import type { Variants } from 'framer-motion';

export const Landing: React.FC = () => {
  const { user } = useAuth();
  const navigate = useNavigate();

  const handleStart = () => {
    if (user) {
      navigate('/dashboard');
    } else {
      navigate('/signup');
    }
  };

  const containerVariants: Variants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.2 },
    },
  };

  const itemVariants: Variants = {
    hidden: { opacity: 0, y: 30 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { type: 'spring', stiffness: 100, damping: 15 },
    },
  };

  return (
    <div className="min-h-screen bg-dark-950 text-white relative overflow-hidden font-sans flex flex-col justify-between">
      {/* Background elements */}
      <div className="absolute top-[-10%] right-[-10%] w-[600px] h-[600px] bg-accent-purple/10 rounded-full blur-[140px] animate-pulse-glow pointer-events-none"></div>
      <div className="absolute bottom-[-10%] left-[-10%] w-[600px] h-[600px] bg-accent-blue/10 rounded-full blur-[140px] animate-pulse-glow pointer-events-none" style={{ animationDelay: '-4s' }}></div>
      <div className="absolute inset-0 bg-[linear-gradient(to_right,rgba(255,255,255,0.01)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,0.01)_1px,transparent_1px)] bg-[size:4rem_4rem] pointer-events-none"></div>

      {/* Header */}
      <header className="w-full max-w-7xl mx-auto px-6 py-6 flex items-center justify-between relative z-10">
        <div className="flex items-center gap-2">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-accent-purple to-accent-blue flex items-center justify-center shadow-lg shadow-accent-purple/20">
            <Wallet className="w-5 h-5 text-white" />
          </div>
          <span className="font-bold text-white text-xl tracking-tight">FinSight AI</span>
        </div>
        <div className="flex items-center gap-4">
          <Link to="/login" className="text-sm font-semibold text-dark-300 hover:text-white transition-colors">
            Sign In
          </Link>
          <button 
            onClick={handleStart}
            className="px-4 py-2 rounded-xl bg-white/5 border border-white/10 hover:border-accent-purple/40 hover:bg-accent-purple/5 text-sm font-semibold text-white transition-all shadow-md"
          >
            {user ? 'Dashboard' : 'Sign Up'}
          </button>
        </div>
      </header>

      {/* Hero Section */}
      <main className="max-w-7xl mx-auto px-6 py-12 lg:py-20 flex-1 flex flex-col lg:flex-row items-center gap-12 relative z-10 w-full">
        {/* Left Column: Text */}
        <motion.div 
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="flex-1 text-center lg:text-left space-y-6"
        >
          <motion.div 
            variants={itemVariants}
            className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent-purple/10 border border-accent-purple/20 text-accent-purple text-xs font-semibold"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>AI-Powered Personal Finance</span>
          </motion.div>
          
          <motion.h1 
            variants={itemVariants}
            className="text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight leading-[1.1] text-white"
          >
            Master Your Money <br />
            With <span className="text-gradient">FinSight AI</span>
          </motion.h1>

          <motion.p 
            variants={itemVariants}
            className="text-dark-400 text-base sm:text-lg max-w-xl mx-auto lg:mx-0 leading-relaxed"
          >
            Track expenses, visualize budgets in real-time, and get tailored AI spending recommendations generated by Google Gemini. Premium finance, simplified.
          </motion.p>

          <motion.div 
            variants={itemVariants}
            className="flex flex-col sm:flex-row justify-center lg:justify-start items-center gap-4 pt-4"
          >
            <button
              onClick={handleStart}
              className="w-full sm:w-auto px-8 py-3.5 rounded-xl bg-gradient-to-r from-accent-purple to-accent-blue hover:from-accent-purple/95 hover:to-accent-blue/95 text-white font-semibold flex items-center justify-center gap-2 shadow-lg shadow-accent-purple/25 group transition-all"
            >
              <span>{user ? 'Go to Dashboard' : 'Start Tracking Free'}</span>
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </button>
            <Link
              to="/login"
              className="w-full sm:w-auto px-8 py-3.5 rounded-xl glass hover:bg-white/5 border border-white/5 text-dark-200 hover:text-white font-semibold text-center transition-all"
            >
              Sign In to Account
            </Link>
          </motion.div>
        </motion.div>

        {/* Right Column: Cards Mockup */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.9, rotateY: 5 }}
          animate={{ opacity: 1, scale: 1, rotateY: 0 }}
          transition={{ type: 'spring', duration: 1, bounce: 0.2 }}
          className="flex-1 w-full max-w-md lg:max-w-none relative"
        >
          <div className="glass-card rounded-2xl p-6 border border-white/10 relative shadow-2xl overflow-hidden group">
            {/* Visual Glass highlights inside the card mockup */}
            <div className="absolute inset-0 bg-gradient-to-br from-accent-purple/5 to-accent-blue/5 pointer-events-none"></div>
            
            <div className="flex justify-between items-center mb-6">
              <div className="space-y-1">
                <span className="text-xs text-dark-500 font-semibold uppercase tracking-wider">Total Balance</span>
                <h3 className="text-3xl font-extrabold text-white">₹1,48,250</h3>
              </div>
              <div className="px-3 py-1 rounded-lg bg-accent-emerald/10 border border-accent-emerald/20 text-accent-emerald text-xs font-semibold">
                +14% this month
              </div>
            </div>

            {/* Spark line dummy */}
            <div className="h-16 flex items-end gap-1 mb-6">
              {[30, 45, 35, 60, 50, 75, 65, 80, 95].map((val, idx) => (
                <div 
                  key={idx} 
                  style={{ height: `${val}%` }} 
                  className="flex-1 bg-gradient-to-t from-accent-purple/80 to-accent-blue/80 rounded-t-sm"
                ></div>
              ))}
            </div>

            {/* AI Floating Card */}
            <motion.div 
              animate={{ y: [0, -8, 0] }}
              transition={{ repeat: Infinity, duration: 4, ease: 'easeInOut' }}
              className="glass p-4 rounded-xl border border-white/10 relative z-20 shadow-xl flex items-start gap-3 mt-4"
            >
              <div className="p-2 rounded-lg bg-accent-purple/20 text-accent-purple shrink-0">
                <Sparkles className="w-5 h-5" />
              </div>
              <div>
                <p className="text-xs font-semibold text-accent-purple">Gemini Assistant</p>
                <p className="text-xs text-dark-300 mt-1">
                  "You spent 40% less on Entertainment compared to last week. Great job, keep saving!"
                </p>
              </div>
            </motion.div>
          </div>
        </motion.div>
      </main>

      {/* Features Grid */}
      <section className="bg-dark-900/40 border-t border-white/5 py-12 relative z-10 w-full">
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="flex gap-4">
            <div className="w-12 h-12 rounded-xl bg-accent-purple/10 border border-accent-purple/20 flex items-center justify-center text-accent-purple shrink-0">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h4 className="text-base font-bold text-white mb-1">Gemini AI Assistant</h4>
              <p className="text-xs text-dark-400 leading-relaxed">Get personalized spending audits, financial summaries, and actionable budgeting recommendations.</p>
            </div>
          </div>

          <div className="flex gap-4">
            <div className="w-12 h-12 rounded-xl bg-accent-blue/10 border border-accent-blue/20 flex items-center justify-center text-accent-blue shrink-0">
              <TrendingUp className="w-5 h-5" />
            </div>
            <div>
              <h4 className="text-base font-bold text-white mb-1">Visual Analytics</h4>
              <p className="text-xs text-dark-400 leading-relaxed">Interactive charts for monthly expenses, income comparison, category splits, and savings trends.</p>
            </div>
          </div>

          <div className="flex gap-4">
            <div className="w-12 h-12 rounded-xl bg-accent-rose/10 border border-accent-rose/20 flex items-center justify-center text-accent-rose shrink-0">
              <BellRing className="w-5 h-5" />
            </div>
            <div>
              <h4 className="text-base font-bold text-white mb-1">Smart Budgets</h4>
              <p className="text-xs text-dark-400 leading-relaxed">Set custom monthly target caps and receive responsive, active warning triggers if you exceed limits.</p>
            </div>
          </div>

          <div className="flex gap-4">
            <div className="w-12 h-12 rounded-xl bg-accent-emerald/10 border border-accent-emerald/20 flex items-center justify-center text-accent-emerald shrink-0">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <h4 className="text-base font-bold text-white mb-1">Secure & Real-time</h4>
              <p className="text-xs text-dark-400 leading-relaxed">Built with Firebase Auth and Firestore subcollections ensuring military-grade user separation and sync.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="w-full max-w-7xl mx-auto px-6 py-6 border-t border-white/5 flex flex-col sm:flex-row justify-between items-center gap-4 text-xs text-dark-500 relative z-10">
        <p>&copy; {new Date().getFullYear()} FinSight AI. All rights reserved.</p>
        <div className="flex gap-4">
          <a href="#" className="hover:text-white transition-colors">Privacy Policy</a>
          <a href="#" className="hover:text-white transition-colors">Terms of Service</a>
        </div>
      </footer>
    </div>
  );
};
export default Landing;
